[package]
name = "cube"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glm = "0.2.3"
hex-literal = "0.3.4"
ieee754 = "0.2.6"
lazy_static = "1.4.0"
num-traits = "0.2.15"
